# [Learn Quantum Computing with Python and Q#](https://www.manning.com/books/learn-quantum-computing-with-python-and-q-sharp?a_aid=learn-qc-granade&a_bid=ee23f338)<br>Appendix C Exercise Solutions
----
> Copyright (c) Sarah Kaiser and Chris Granade.
> Code sample from the book "Learn Quantum Computing with Python and Q#" by
> Sarah Kaiser and Chris Granade, published by Manning Publications Co.
> Book ISBN 9781617296130.
> Code licensed under the MIT License.


### Preamble

In [1]:
import numpy as np


### Exercise B.1 

**What would 25 meters West and 110 meters North be in feet?**

In [2]:
directions_in_meters = np.array([[-25], [110]])
directions_in_feet = 3.28 * directions_in_meters
directions_in_feet

array([[-82. ],
       [360.8]])

----
### Exercise B.2

**Which of the following functions are linear?**

- $f(x) = 2x$
- $f(x) = x^2$
- $f(x) = 2^x$

Recall that a function $f$ is linear if and only if for all scalars $a$ and $b$, $f(ax + by) = af(x) + bf(y)$.
Let's check this condition for each of the three functions above:

- $f(ax + by) = 2(ax + by) = 2ax + 2by = a \times 2x + b \times 2y = af(x) + bf(y)$, thus this function is linear.
- $f(ax + by) = (ax + by)^2 = a^2 x^2 + 2abxy + b^2 y^2$, but $af(x) + bf(y) = ax^2 + by^2$. Since $a \ne a^2$ for all $a$, and since the second expression is missing the $2abxy$ term, you can conclude that this function is **not** linear.
- $f(ax + by) = 2^{ax + by} = 2^{ax} \times 2^{by}$, but $af(x) + bf(y) = a2^x + b2^y$. These two expressions aren't the same, so you can conclude that this function is **not** linear.

----
### Exercise B.3

**Suppose that you have a linear function $g$ such that $g([[1], [0]]) = [[2.3], [-3.1]]$ and $g([[0], [1]]) = [[-5.2], [0.7]]$.
Compute $g([[2], [-2]])$.**

In [3]:
g_horizontal = np.array([[2.3], [-3.1]])
g_vertical = np.array([[-5.2], [0.7]])

2 * g_horizontal + (-2) * g_vertical

array([[15. ],
       [-7.6]])

----
### Exercise B.4

**Let $X$ be the matrix $[[0, 1], [1, 0]]$, and let $\vec{y}$ be the vector $[[2], [3]]$.
Using NumPy, compute $X\vec{y}$ and $XX$.**

In [4]:
X = np.array([
    [0, 1],
    [1, 0]
])
y = np.array([
    [2],
    [3]
])

In [5]:
X @ y

array([[3],
       [2]])

In [6]:
X @ X

array([[1, 0],
       [0, 1]])

----
### Exercise B.5

**Given a vector $[[2], [3]]$, find a vector that points in the same direction but with length 1.**

*HINT*: You can either do this by using an inner product, or the `np.linalg.norm` function.

In [7]:
v = np.array([
    [2],
    [3]
])

We can try both ways suggested by the hint above to confirm that you get the same answer from each.

In [8]:
v / np.sqrt(v.transpose() @ v)

array([[0.5547002 ],
       [0.83205029]])

In [9]:
v / np.linalg.norm(v)

array([[0.5547002 ],
       [0.83205029]])