# [Learn Quantum Computing with Python and Q#](https://www.manning.com/books/learn-quantum-computing-with-python-and-q-sharp?a_aid=learn-qc-granade&a_bid=ee23f338)<br>Chapter 5 Exercise Solutions
----
> Copyright (c) Sarah Kaiser and Chris Granade.
> Code sample from the book "Learn Quantum Computing with Python and Q#" by
> Sarah Kaiser and Chris Granade, published by Manning Publications Co.
> Book ISBN 9781617296130.
> Code licensed under the MIT License.

### Preamble

In [1]:
import numpy as np
import qutip as qt

### Exercise 5.1

**Say you have a register with 3 qubits, in the state |01+⟩. Using QuTiP, write out this state, and then swap the second and third qubits so your register is in the |0+1⟩ state.**

*HINT*: since nothing will happen to the first qubit, make sure to tensor an identity matrix to `qt.swap` to build up the correct operation for your register.

In [2]:
ket0 = qt.basis(2, 0)
ket1 = qt.basis(2, 1)
ket_plus = qt.Qobj([
    [1],
    [1]
]) / np.sqrt(2)

In [3]:
initial_state = qt.tensor(ket0, ket1, ket_plus)
initial_state

Quantum object: dims = [[2, 2, 2], [1, 1, 1]], shape = (8, 1), type = ket
Qobj data =
[[0.        ]
 [0.        ]
 [0.70710678]
 [0.70710678]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]]

In [4]:
qt.tensor(qt.qeye(2), qt.qip.operations.swap()) * initial_state

Quantum object: dims = [[2, 2, 2], [1, 1, 1]], shape = (8, 1), type = ket
Qobj data =
[[0.        ]
 [0.70710678]
 [0.        ]
 [0.70710678]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]]

In [5]:
qt.tensor(ket0, ket_plus, ket1)

Quantum object: dims = [[2, 2, 2], [1, 1, 1]], shape = (8, 1), type = ket
Qobj data =
[[0.        ]
 [0.70710678]
 [0.        ]
 [0.70710678]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]]

----
### Exercise 5.2

**Suppose you prepare a qubit in the |−⟩ state and apply a `z` rotation.
If you measure along the 𝑋 axis, what would you get?
What would you measure if you apply two `z` rotations?
If you had to implement those same two rotations with `rz`, what angles would you use?**

Recall that the `z` operation is represented by the unitary matrix returned by `qt.sigmaz()`.
Thus, you can figure out what `z` does to a qubit in the $|-\rangle$ state by using that matrix:

In [6]:
ket_minus = qt.Qobj([
    [1],
    [-1]
]) / np.sqrt(2)

In [7]:
qt.sigmaz() * ket_minus

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.70710678]
 [0.70710678]]

We recognize this being the state vector $|+\rangle$, so that we'll always get a "0" result when measuring along the 𝑋-axis.

Applying a second `z` instruction takes us back to $|-\rangle$, however:

In [8]:
qt.sigmaz() * qt.sigmaz() * ket_minus

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[ 0.70710678]
 [-0.70710678]]

If you wanted to use an `rz` instruction instead of `z`, you would need a rotation of $\pi$:

In [9]:
qt.qip.operations.rz(np.pi) * ket_minus

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.-0.70710678j]
 [0.-0.70710678j]]

Notice that this is different from $|+\rangle$ only by a global phase of $-i$.

In [10]:
qt.qip.operations.rz(np.pi) * ket_minus / -1j

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.70710678]
 [0.70710678]]

----
### Exercise 5.3

**Use the `qt.sigmay()` function to make a table similar to the one for the `z` instruction, but for the `y` instruction.**

The "truth table" in the main body for the `z` instruction listed what the `z` instruction does for qubits in each of the input states |0⟩, |1⟩, |+⟩, and |−⟩.
While that's overcomplete in the sense that you can infer what `z` does from its action on the |0⟩ or |1⟩ states alone (or on the |+⟩ and |−⟩ states alone), it's helpful to keep in mind, so let's write out the same here for `y`.

In [11]:
ket0 = qt.basis(2, 0)
ket1 = qt.basis(2, 1)
ket_plus = qt.Qobj([
    [1],
    [1]
]) / np.sqrt(2)
ket_minus = qt.Qobj([
    [1],
    [-1]
]) / np.sqrt(2)

In [12]:
qt.sigmay() * ket0

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.+0.j]
 [0.+1.j]]

In [13]:
qt.sigmay() * ket1

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.-1.j]
 [0.+0.j]]

In [14]:
qt.sigmay() * ket_plus

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.-0.70710678j]
 [0.+0.70710678j]]

In [15]:
qt.sigmay() * ket_minus

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.+0.70710678j]
 [0.+0.70710678j]]

Using these four results, you can complete now the table:

| Input | Output |
|---|---|
| \|0⟩ | 𝑖\|0⟩ |
| \|1⟩ | −𝑖\|1⟩ |
| \|+⟩ | −𝑖\|−⟩ |
| \|−⟩ | 𝑖\|+⟩ |

----
### Exercise 5.4

**We've only checked that one measurement probability is still the same, but maybe the probabilities have changed for 𝑋 or 𝑌 measurements.
To fully check that the global phase doesn't change anything, prepare the same state and rotation as in Listing 5.10 and check that the probabilities of measuring the state along the 𝑋 or 𝑌 axis aren't changed by applying an `rz` instruction.**

Recall that the state $|\psi\rangle$ was prepared by an `rz` instruction acting on a qubit in the |0⟩ state.

In [16]:
ket0 = qt.basis(2, 0)
ket1 = qt.basis(2, 1)
ket_plus = qt.Qobj([
    [1],
    [1]
]).unit()
ket_psi = qt.qip.operations.rz(np.pi / 3) * ket0
ket_psi

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.8660254-0.5j]
 [0.       +0.j ]]

To confirm that this state is indistinguishable from the |0⟩ state before applying a global phase, we can check that the overlap with the |+⟩ and $(|0\rangle + i|1\rangle) / \sqrt{2}$ states is left the same (namely, that measurement probabilities are left at 50/50):

In [17]:
np.abs((ket_plus.dag() * ket_psi)[0, 0]) ** 2

0.4999999999999999

In [18]:
np.abs(((ket0 + 1j * ket1).unit().dag() * ket_psi)[0, 0]) ** 2

0.4999999999999999

----
### Exercise 5.5

**The $\left(\left|00\right\rangle + \left|11\right\rangle\right) / \sqrt{2}$ state that we've seen a few times now isn't the only example of an entangled state.
In fact, if you pick a two-qubit state at random, it is almost certainly going to be entangled.
Just as the computational basis $\left\{\left|00\right\rangle, \left|01\right\rangle, \left|10\right\rangle, \left|11\right\rangle\right\}$ is a particularly useful set of unentangled states, there's a set of four particular entangled states known as the _Bell basis_ after physicist John Stewart Bell.**

| Name | Expansion in computational basis |
|---|---|
| \|β₀₀⟩ | (\|00⟩ + \|11⟩) / √2 |
| \|β₀₁⟩ | (\|00⟩ − \|11⟩) / √2 |
| \|β₁₀⟩ | (\|01⟩ + \|10⟩) / √2 |
| \|β₁₁⟩ | (\|01⟩ − \|10⟩) / √2 |

**Using what you've learned about the `cnot` instruction and the Pauli instructions (`x`, `y`, and `z`), write programs to prepare each of the four Bell states in the table above.**

*HINT*: Table 5.2 should be very helpful in this exercise.

For this exercise, let's use the shiny new simulator that you put together during this Chapter!

In [19]:
import simulator

In [20]:
device = simulator.Simulator(capacity=2)

Recall that we can use the `h` and `cnot` instructions together to prepare a two-qubit register in a Bell pair.

In [21]:
with device.using_register(2) as (left, right):
    left.h()
    left.cnot(right)
    device.dump()

Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[0.70710678]
 [0.        ]
 [0.        ]
 [0.70710678]]


To get the other three Bell basis states, we can use Pauli instructions on the first qubit alone.

In [22]:
with device.using_register(2) as (left, right):
    left.h()
    left.cnot(right)
    
    left.x()
    
    device.dump()

Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[0.        ]
 [0.70710678]
 [0.70710678]
 [0.        ]]


In [23]:
with device.using_register(2) as (left, right):
    left.h()
    left.cnot(right)
    
    left.z()
    
    device.dump()

Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[ 0.70710678]
 [ 0.        ]
 [ 0.        ]
 [-0.70710678]]


In [24]:
with device.using_register(2) as (left, right):
    left.h()
    left.cnot(right)
    
    left.x()
    left.z()
    
    device.dump()

Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[ 0.        ]
 [-0.70710678]
 [ 0.70710678]
 [ 0.        ]]


Note that you could also have applied your Pauli instructions to the second qubit as well; this is a unique symmetry of the Bell basis states, and one of the things that makes them really neat to work with.

In [25]:
with device.using_register(2) as (left, right):
    left.h()
    left.cnot(right)
    
    right.x()
    right.z()
    
    device.dump()

Quantum object: dims = [[2, 2], [1, 1]], shape = (4, 1), type = ket
Qobj data =
[[ 0.        ]
 [-0.70710678]
 [ 0.70710678]
 [ 0.        ]]


----
### Exercise 5.6

**Try changing your operation or Eve's operation to convince yourself that you only get a |000⟩ state at the end if you undo the same operation that Eve applied to her qubit.**

In [26]:
import simulator
from teleport import teleport

In [27]:
sim = simulator.Simulator(capacity=3)
with sim.using_register(3) as (msg, here, there):
    msg.ry(0.123)
    teleport(msg, here, there)

    there.h()
    sim.dump()   

Quantum object: dims = [[2, 2, 2], [1, 1, 1]], shape = (8, 1), type = ket
Qobj data =
[[0.74922963]
 [0.66231032]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]]
